export type Name =
	| "foregroundNeutral"
	| "foregroundNeutralFaded"
	| "foregroundDisabled"
	| "foregroundPrimary"
	| "foregroundCritical"
	| "foregroundWarning"
	| "foregroundPositive"
	| "borderNeutral"
	| "borderNeutralFaded"
	| "borderDisabled"
	| "borderPrimary"
	| "borderPrimaryFaded"
	| "borderCritical"
	| "borderCriticalFaded"
	| "borderWarning"
	| "borderWarningFaded"
	| "borderPositive"
	| "borderPositiveFaded"
	| "backgroundNeutral"
	| "backgroundNeutralFaded"
	| "backgroundDisabled"
	| "backgroundDisabledFaded"
	| "backgroundPrimary"
	| "backgroundPrimaryFaded"
	| "backgroundCritical"
	| "backgroundCriticalFaded"
	| "backgroundWarning"
	| "backgroundWarningFaded"
	| "backgroundPositive"
	| "backgroundPositiveFaded"
	| "backgroundPage"
	| "backgroundPageFaded"
	| "backgroundElevationBase"
	| "backgroundElevationRaised"
	| "backgroundElevationOverlay"
	| "brand"
	| "white"
	| "black";

export type GeneratedOnName =
	| "onBackgroundNeutral"
	| "onBackgroundPrimary"
	| "onBackgroundPositive"
	| "onBackgroundWarning"
	| "onBackgroundCritical";

export type GeneratedRGBName =
	| "rgbBackgroundNeutral"
	| "rgbBackgroundNeutralFaded"
	| "rgbBackgroundDisabled"
	| "rgbBackgroundDisabledFaded"
	| "rgbBackgroundPrimary"
	| "rgbBackgroundPrimaryFaded"
	| "rgbBackgroundCritical"
	| "rgbBackgroundCriticalFaded"
	| "rgbBackgroundWarning"
	| "rgbBackgroundWarningFaded"
	| "rgbBackgroundPositive"
	| "rgbBackgroundPositiveFaded"
	| "rgbBackgroundPage"
	| "rgbBackgroundPageFaded"
	| "rgbBackgroundElevationBase"
	| "rgbBackgroundElevationRaised"
	| "rgbBackgroundElevationOverlay";

export type Token = { hex: string; hexDark?: string };
