name: "pull-request"
on:
  pull_request:
    branches:
      - main

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn --check-files
      - run: yarn playwright install
      - run: yarn lint
      - run: yarn build
      - run: yarn test:browser
      - run: yarn test:unit
      - uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
